spring:
  threads:
    virtual:
      enabled: true
  application:
    name: PandaMonitorBackend
config:
  db-url: ${DB_URL}
  db-username: ${DB_USERNAME}
  db-password: ${DB_PASSWORD}

jimmer:
  language: kotlin
  client:
    ts:
      path: /ts.zip
    openapi:
      path: /api/openapi.yml
      ui-path: /api/openapi.html
      properties:
        info:
          title: Panda Monitor
          version: 1.0.0
          description: Panda Monitor API