spring:
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  application:
    name: PandaMonitorBackend
config:
  db-url: ${DB_URL}
  db-username: ${DB_USERNAME}
  db-password: ${DB_PASSWORD}

jimmer:
  language: kotlin
